server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/online_banking
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=rajkumar
spring.datasource.password=Raj@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration (development secret – replace in prod)
app.jwt-secret=MzJieXRlU2VjcmV0S2V5UmVhZFRlbXBsYXRlU2VjcmV0MTIzNDU2
app.jwt-expiration-milliseconds=864000000

# Logging Configuration
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.banking=DEBUG
